export enum MarkerIcon {
  JS = 'javascript',
  HTML = 'html',
  PHP = 'php',
  RUBY = 'ruby',
  PYTHON = 'python',
  NET = 'net',
  JAVA = 'java',
  Scala = 'scala',
  C = 'c',
  Mobile = 'mobile',
  TESTING = 'testing',
  DEVOPS = 'devops',
  ADMIN = 'admin',
  UX = 'ux',
  PM = 'pm',
  GAME = 'game',
  ANALYTICS = 'analytics',
  SECURITY = 'security',
  DATA = 'data',
  GO ='go',
  SUPPORT = 'support',
  ERP = 'erp',
  ARCHITECTURE = 'architecture',
  OTHER = 'other',

}